export map=(
    "/usr/include/wayland-client-core.h;scripts/../stubs/headers/wayland-client-core.h"
    "/usr/include/wayland-client-protocol.h;scripts/../stubs/headers/wayland-client-protocol.h"
    "/usr/include/wayland-client.h;scripts/../stubs/headers/wayland-client.h"
    "/usr/include/wayland-cursor.h;scripts/../stubs/headers/wayland-cursor.h"
    "/usr/include/wayland-egl-backend.h;scripts/../stubs/headers/wayland-egl-backend.h"
    "/usr/include/wayland-egl-core.h;scripts/../stubs/headers/wayland-egl-core.h"
    "/usr/include/wayland-egl.h;scripts/../stubs/headers/wayland-egl.h"
    "/usr/include/wayland-server-core.h;scripts/../stubs/headers/wayland-server-core.h"
    "/usr/include/wayland-server-protocol.h;scripts/../stubs/headers/wayland-server-protocol.h"
    "/usr/include/wayland-server.h;scripts/../stubs/headers/wayland-server.h"
    "/usr/include/wayland-util.h;scripts/../stubs/headers/wayland-util.h"
    "/usr/include/wayland-version.h;scripts/../stubs/headers/wayland-version.h"
    "/usr/include/X11;scripts/../stubs/headers/X11"
    "/usr/include/ffi.h;scripts/../stubs/headers/ffi.h"
    "/usr/include/ffitarget.h;scripts/../stubs/headers/ffitarget.h"
)