// Based on vkoskiv's cosmo-sdl-template under the MIT license.
// See https://github.com/vkoskiv/cosmo-sdl-template/
// See https://github.com/vkoskiv/cosmo-sdl-template/blob/master/LICENSE

#include "gir_stub.h"
#include "../stub.h"
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>

#define _COSMO_SOURCE
#include <libc/dlopen/dlfcn.h>

void initialize_gir(void) {
    char* candidates[] = { "libgirepository-2.0.so" };

    void *gir_lib_ptr = try_find_lib(candidates, LEN(candidates));

    if (!gir_lib_ptr) {
        fprintf(stderr, "Unable to locate gir, exiting!");
        exit(1);
    }

    girepository = calloc(1, sizeof(*girepository));
    *girepository = (struct girepository_syms) {
        .lib = gir_lib_ptr,
        // DLSYM_girepository_HERE
        .gi_arg_info_is_return_value = try_find_sym(gir_lib_ptr, "gi_arg_info_is_return_value"),
        .gi_arg_info_is_optional = try_find_sym(gir_lib_ptr, "gi_arg_info_is_optional"),
        .gi_arg_info_is_caller_allocates = try_find_sym(gir_lib_ptr, "gi_arg_info_is_caller_allocates"),
        .gi_arg_info_may_be_null = try_find_sym(gir_lib_ptr, "gi_arg_info_may_be_null"),
        .gi_arg_info_is_skip = try_find_sym(gir_lib_ptr, "gi_arg_info_is_skip"),
        .gi_arg_info_get_ownership_transfer = try_find_sym(gir_lib_ptr, "gi_arg_info_get_ownership_transfer"),
        .gi_arg_info_get_scope = try_find_sym(gir_lib_ptr, "gi_arg_info_get_scope"),
        .gi_arg_info_get_closure_index = try_find_sym(gir_lib_ptr, "gi_arg_info_get_closure_index"),
        .gi_arg_info_get_destroy_index = try_find_sym(gir_lib_ptr, "gi_arg_info_get_destroy_index"),
        .gi_arg_info_get_type_info = try_find_sym(gir_lib_ptr, "gi_arg_info_get_type_info"),
        .gi_arg_info_load_type_info = try_find_sym(gir_lib_ptr, "gi_arg_info_load_type_info"),
        .gi_arg_info_get_direction = try_find_sym(gir_lib_ptr, "gi_arg_info_get_direction"),
        .gi_base_info_ref = try_find_sym(gir_lib_ptr, "gi_base_info_ref"),
        .gi_base_info_unref = try_find_sym(gir_lib_ptr, "gi_base_info_unref"),
        .gi_base_info_clear = try_find_sym(gir_lib_ptr, "gi_base_info_clear"),
        .gi_base_info_get_name = try_find_sym(gir_lib_ptr, "gi_base_info_get_name"),
        .gi_base_info_get_namespace = try_find_sym(gir_lib_ptr, "gi_base_info_get_namespace"),
        .gi_base_info_is_deprecated = try_find_sym(gir_lib_ptr, "gi_base_info_is_deprecated"),
        .gi_base_info_get_attribute = try_find_sym(gir_lib_ptr, "gi_base_info_get_attribute"),
        .gi_base_info_iterate_attributes = try_find_sym(gir_lib_ptr, "gi_base_info_iterate_attributes"),
        .gi_base_info_get_container = try_find_sym(gir_lib_ptr, "gi_base_info_get_container"),
        .gi_base_info_get_typelib = try_find_sym(gir_lib_ptr, "gi_base_info_get_typelib"),
        .gi_base_info_equal = try_find_sym(gir_lib_ptr, "gi_base_info_equal"),
        .gi_base_info_get_type = try_find_sym(gir_lib_ptr, "gi_base_info_get_type"),
        .gi_callable_info_can_throw_gerror = try_find_sym(gir_lib_ptr, "gi_callable_info_can_throw_gerror"),
        .gi_callable_info_get_return_type = try_find_sym(gir_lib_ptr, "gi_callable_info_get_return_type"),
        .gi_callable_info_load_return_type = try_find_sym(gir_lib_ptr, "gi_callable_info_load_return_type"),
        .gi_callable_info_get_return_attribute = try_find_sym(gir_lib_ptr, "gi_callable_info_get_return_attribute"),
        .gi_callable_info_iterate_return_attributes = try_find_sym(gir_lib_ptr, "gi_callable_info_iterate_return_attributes"),
        .gi_callable_info_get_caller_owns = try_find_sym(gir_lib_ptr, "gi_callable_info_get_caller_owns"),
        .gi_callable_info_may_return_null = try_find_sym(gir_lib_ptr, "gi_callable_info_may_return_null"),
        .gi_callable_info_skip_return = try_find_sym(gir_lib_ptr, "gi_callable_info_skip_return"),
        .gi_callable_info_get_n_args = try_find_sym(gir_lib_ptr, "gi_callable_info_get_n_args"),
        .gi_callable_info_get_arg = try_find_sym(gir_lib_ptr, "gi_callable_info_get_arg"),
        .gi_callable_info_load_arg = try_find_sym(gir_lib_ptr, "gi_callable_info_load_arg"),
        .gi_callable_info_invoke = try_find_sym(gir_lib_ptr, "gi_callable_info_invoke"),
        .gi_callable_info_get_instance_ownership_transfer = try_find_sym(gir_lib_ptr, "gi_callable_info_get_instance_ownership_transfer"),
        .gi_callable_info_is_method = try_find_sym(gir_lib_ptr, "gi_callable_info_is_method"),
        .gi_constant_info_free_value = try_find_sym(gir_lib_ptr, "gi_constant_info_free_value"),
        .gi_constant_info_get_value = try_find_sym(gir_lib_ptr, "gi_constant_info_get_value"),
        .gi_constant_info_get_type_info = try_find_sym(gir_lib_ptr, "gi_constant_info_get_type_info"),
        .gi_enum_info_get_value = try_find_sym(gir_lib_ptr, "gi_enum_info_get_value"),
        .gi_enum_info_get_n_methods = try_find_sym(gir_lib_ptr, "gi_enum_info_get_n_methods"),
        .gi_enum_info_get_method = try_find_sym(gir_lib_ptr, "gi_enum_info_get_method"),
        .gi_enum_info_get_storage_type = try_find_sym(gir_lib_ptr, "gi_enum_info_get_storage_type"),
        .gi_enum_info_get_error_domain = try_find_sym(gir_lib_ptr, "gi_enum_info_get_error_domain"),
        .gi_enum_info_get_n_values = try_find_sym(gir_lib_ptr, "gi_enum_info_get_n_values"),
        .gi_field_info_get_size = try_find_sym(gir_lib_ptr, "gi_field_info_get_size"),
        .gi_field_info_get_offset = try_find_sym(gir_lib_ptr, "gi_field_info_get_offset"),
        .gi_field_info_get_type_info = try_find_sym(gir_lib_ptr, "gi_field_info_get_type_info"),
        .gi_field_info_get_field = try_find_sym(gir_lib_ptr, "gi_field_info_get_field"),
        .gi_field_info_set_field = try_find_sym(gir_lib_ptr, "gi_field_info_set_field"),
        .gi_field_info_get_flags = try_find_sym(gir_lib_ptr, "gi_field_info_get_flags"),
        .gi_function_info_get_flags = try_find_sym(gir_lib_ptr, "gi_function_info_get_flags"),
        .gi_function_info_get_property = try_find_sym(gir_lib_ptr, "gi_function_info_get_property"),
        .gi_function_info_get_vfunc = try_find_sym(gir_lib_ptr, "gi_function_info_get_vfunc"),
        .gi_invoke_error_quark = try_find_sym(gir_lib_ptr, "gi_invoke_error_quark"),
        .gi_function_info_invoke = try_find_sym(gir_lib_ptr, "gi_function_info_invoke"),
        .gi_function_info_get_symbol = try_find_sym(gir_lib_ptr, "gi_function_info_get_symbol"),
        .gi_interface_info_get_prerequisite = try_find_sym(gir_lib_ptr, "gi_interface_info_get_prerequisite"),
        .gi_interface_info_get_n_properties = try_find_sym(gir_lib_ptr, "gi_interface_info_get_n_properties"),
        .gi_interface_info_get_property = try_find_sym(gir_lib_ptr, "gi_interface_info_get_property"),
        .gi_interface_info_get_n_methods = try_find_sym(gir_lib_ptr, "gi_interface_info_get_n_methods"),
        .gi_interface_info_get_method = try_find_sym(gir_lib_ptr, "gi_interface_info_get_method"),
        .gi_interface_info_find_method = try_find_sym(gir_lib_ptr, "gi_interface_info_find_method"),
        .gi_interface_info_get_n_signals = try_find_sym(gir_lib_ptr, "gi_interface_info_get_n_signals"),
        .gi_interface_info_get_signal = try_find_sym(gir_lib_ptr, "gi_interface_info_get_signal"),
        .gi_interface_info_find_signal = try_find_sym(gir_lib_ptr, "gi_interface_info_find_signal"),
        .gi_interface_info_get_n_vfuncs = try_find_sym(gir_lib_ptr, "gi_interface_info_get_n_vfuncs"),
        .gi_interface_info_get_vfunc = try_find_sym(gir_lib_ptr, "gi_interface_info_get_vfunc"),
        .gi_interface_info_find_vfunc = try_find_sym(gir_lib_ptr, "gi_interface_info_find_vfunc"),
        .gi_interface_info_get_n_constants = try_find_sym(gir_lib_ptr, "gi_interface_info_get_n_constants"),
        .gi_interface_info_get_constant = try_find_sym(gir_lib_ptr, "gi_interface_info_get_constant"),
        .gi_interface_info_get_iface_struct = try_find_sym(gir_lib_ptr, "gi_interface_info_get_iface_struct"),
        .gi_interface_info_get_n_prerequisites = try_find_sym(gir_lib_ptr, "gi_interface_info_get_n_prerequisites"),
        .gi_object_info_get_type_init_function_name = try_find_sym(gir_lib_ptr, "gi_object_info_get_type_init_function_name"),
        .gi_object_info_get_abstract = try_find_sym(gir_lib_ptr, "gi_object_info_get_abstract"),
        .gi_object_info_get_final = try_find_sym(gir_lib_ptr, "gi_object_info_get_final"),
        .gi_object_info_get_fundamental = try_find_sym(gir_lib_ptr, "gi_object_info_get_fundamental"),
        .gi_object_info_get_parent = try_find_sym(gir_lib_ptr, "gi_object_info_get_parent"),
        .gi_object_info_get_n_interfaces = try_find_sym(gir_lib_ptr, "gi_object_info_get_n_interfaces"),
        .gi_object_info_get_interface = try_find_sym(gir_lib_ptr, "gi_object_info_get_interface"),
        .gi_object_info_get_n_fields = try_find_sym(gir_lib_ptr, "gi_object_info_get_n_fields"),
        .gi_object_info_get_field = try_find_sym(gir_lib_ptr, "gi_object_info_get_field"),
        .gi_object_info_get_n_properties = try_find_sym(gir_lib_ptr, "gi_object_info_get_n_properties"),
        .gi_object_info_get_property = try_find_sym(gir_lib_ptr, "gi_object_info_get_property"),
        .gi_object_info_get_n_methods = try_find_sym(gir_lib_ptr, "gi_object_info_get_n_methods"),
        .gi_object_info_get_method = try_find_sym(gir_lib_ptr, "gi_object_info_get_method"),
        .gi_object_info_find_method = try_find_sym(gir_lib_ptr, "gi_object_info_find_method"),
        .gi_object_info_find_method_using_interfaces = try_find_sym(gir_lib_ptr, "gi_object_info_find_method_using_interfaces"),
        .gi_object_info_get_n_signals = try_find_sym(gir_lib_ptr, "gi_object_info_get_n_signals"),
        .gi_object_info_get_signal = try_find_sym(gir_lib_ptr, "gi_object_info_get_signal"),
        .gi_object_info_find_signal = try_find_sym(gir_lib_ptr, "gi_object_info_find_signal"),
        .gi_object_info_get_n_vfuncs = try_find_sym(gir_lib_ptr, "gi_object_info_get_n_vfuncs"),
        .gi_object_info_get_vfunc = try_find_sym(gir_lib_ptr, "gi_object_info_get_vfunc"),
        .gi_object_info_find_vfunc = try_find_sym(gir_lib_ptr, "gi_object_info_find_vfunc"),
        .gi_object_info_find_vfunc_using_interfaces = try_find_sym(gir_lib_ptr, "gi_object_info_find_vfunc_using_interfaces"),
        .gi_object_info_get_n_constants = try_find_sym(gir_lib_ptr, "gi_object_info_get_n_constants"),
        .gi_object_info_get_constant = try_find_sym(gir_lib_ptr, "gi_object_info_get_constant"),
        .gi_object_info_get_class_struct = try_find_sym(gir_lib_ptr, "gi_object_info_get_class_struct"),
        .gi_object_info_get_ref_function_name = try_find_sym(gir_lib_ptr, "gi_object_info_get_ref_function_name"),
        .gi_object_info_get_ref_function_pointer = try_find_sym(gir_lib_ptr, "gi_object_info_get_ref_function_pointer"),
        .gi_object_info_get_unref_function_name = try_find_sym(gir_lib_ptr, "gi_object_info_get_unref_function_name"),
        .gi_object_info_get_unref_function_pointer = try_find_sym(gir_lib_ptr, "gi_object_info_get_unref_function_pointer"),
        .gi_object_info_get_set_value_function_name = try_find_sym(gir_lib_ptr, "gi_object_info_get_set_value_function_name"),
        .gi_object_info_get_set_value_function_pointer = try_find_sym(gir_lib_ptr, "gi_object_info_get_set_value_function_pointer"),
        .gi_object_info_get_get_value_function_name = try_find_sym(gir_lib_ptr, "gi_object_info_get_get_value_function_name"),
        .gi_object_info_get_get_value_function_pointer = try_find_sym(gir_lib_ptr, "gi_object_info_get_get_value_function_pointer"),
        .gi_object_info_get_type_name = try_find_sym(gir_lib_ptr, "gi_object_info_get_type_name"),
        .gi_property_info_get_type_info = try_find_sym(gir_lib_ptr, "gi_property_info_get_type_info"),
        .gi_property_info_get_ownership_transfer = try_find_sym(gir_lib_ptr, "gi_property_info_get_ownership_transfer"),
        .gi_property_info_get_setter = try_find_sym(gir_lib_ptr, "gi_property_info_get_setter"),
        .gi_property_info_get_getter = try_find_sym(gir_lib_ptr, "gi_property_info_get_getter"),
        .gi_property_info_get_flags = try_find_sym(gir_lib_ptr, "gi_property_info_get_flags"),
        .gi_registered_type_info_get_type_init_function_name = try_find_sym(gir_lib_ptr, "gi_registered_type_info_get_type_init_function_name"),
        .gi_registered_type_info_get_g_type = try_find_sym(gir_lib_ptr, "gi_registered_type_info_get_g_type"),
        .gi_registered_type_info_is_boxed = try_find_sym(gir_lib_ptr, "gi_registered_type_info_is_boxed"),
        .gi_registered_type_info_get_type_name = try_find_sym(gir_lib_ptr, "gi_registered_type_info_get_type_name"),
        .gi_repository_prepend_search_path = try_find_sym(gir_lib_ptr, "gi_repository_prepend_search_path"),
        .gi_repository_prepend_library_path = try_find_sym(gir_lib_ptr, "gi_repository_prepend_library_path"),
        .gi_repository_get_search_path = try_find_sym(gir_lib_ptr, "gi_repository_get_search_path"),
        .gi_repository_get_library_path = try_find_sym(gir_lib_ptr, "gi_repository_get_library_path"),
        .gi_repository_load_typelib = try_find_sym(gir_lib_ptr, "gi_repository_load_typelib"),
        .gi_repository_is_registered = try_find_sym(gir_lib_ptr, "gi_repository_is_registered"),
        .gi_repository_find_by_name = try_find_sym(gir_lib_ptr, "gi_repository_find_by_name"),
        .gi_repository_enumerate_versions = try_find_sym(gir_lib_ptr, "gi_repository_enumerate_versions"),
        .gi_repository_require = try_find_sym(gir_lib_ptr, "gi_repository_require"),
        .gi_repository_require_private = try_find_sym(gir_lib_ptr, "gi_repository_require_private"),
        .gi_repository_get_immediate_dependencies = try_find_sym(gir_lib_ptr, "gi_repository_get_immediate_dependencies"),
        .gi_repository_get_dependencies = try_find_sym(gir_lib_ptr, "gi_repository_get_dependencies"),
        .gi_repository_get_loaded_namespaces = try_find_sym(gir_lib_ptr, "gi_repository_get_loaded_namespaces"),
        .gi_repository_find_by_gtype = try_find_sym(gir_lib_ptr, "gi_repository_find_by_gtype"),
        .gi_repository_get_object_gtype_interfaces = try_find_sym(gir_lib_ptr, "gi_repository_get_object_gtype_interfaces"),
        .gi_repository_get_n_infos = try_find_sym(gir_lib_ptr, "gi_repository_get_n_infos"),
        .gi_repository_get_info = try_find_sym(gir_lib_ptr, "gi_repository_get_info"),
        .gi_repository_find_by_error_domain = try_find_sym(gir_lib_ptr, "gi_repository_find_by_error_domain"),
        .gi_repository_get_typelib_path = try_find_sym(gir_lib_ptr, "gi_repository_get_typelib_path"),
        .gi_repository_get_shared_libraries = try_find_sym(gir_lib_ptr, "gi_repository_get_shared_libraries"),
        .gi_repository_get_c_prefix = try_find_sym(gir_lib_ptr, "gi_repository_get_c_prefix"),
        .gi_repository_get_version = try_find_sym(gir_lib_ptr, "gi_repository_get_version"),
        .gi_repository_get_option_group = try_find_sym(gir_lib_ptr, "gi_repository_get_option_group"),
        .gi_repository_dump = try_find_sym(gir_lib_ptr, "gi_repository_dump"),
        .gi_repository_error_quark = try_find_sym(gir_lib_ptr, "gi_repository_error_quark"),
        .gi_cclosure_marshal_generic = try_find_sym(gir_lib_ptr, "gi_cclosure_marshal_generic"),
        .gi_repository_new = try_find_sym(gir_lib_ptr, "gi_repository_new"),
        .gi_type_info_get_ffi_type = try_find_sym(gir_lib_ptr, "gi_type_info_get_ffi_type"),
        .gi_type_info_extract_ffi_return_value = try_find_sym(gir_lib_ptr, "gi_type_info_extract_ffi_return_value"),
        .gi_type_tag_extract_ffi_return_value = try_find_sym(gir_lib_ptr, "gi_type_tag_extract_ffi_return_value"),
        .gi_function_info_prep_invoker = try_find_sym(gir_lib_ptr, "gi_function_info_prep_invoker"),
        .gi_function_invoker_new_for_address = try_find_sym(gir_lib_ptr, "gi_function_invoker_new_for_address"),
        .gi_function_invoker_clear = try_find_sym(gir_lib_ptr, "gi_function_invoker_clear"),
        .gi_callable_info_create_closure = try_find_sym(gir_lib_ptr, "gi_callable_info_create_closure"),
        .gi_callable_info_get_closure_native_address = try_find_sym(gir_lib_ptr, "gi_callable_info_get_closure_native_address"),
        .gi_callable_info_destroy_closure = try_find_sym(gir_lib_ptr, "gi_callable_info_destroy_closure"),
        .gi_type_tag_get_ffi_type = try_find_sym(gir_lib_ptr, "gi_type_tag_get_ffi_type"),
        .gi_signal_info_get_class_closure = try_find_sym(gir_lib_ptr, "gi_signal_info_get_class_closure"),
        .gi_signal_info_true_stops_emit = try_find_sym(gir_lib_ptr, "gi_signal_info_true_stops_emit"),
        .gi_signal_info_get_flags = try_find_sym(gir_lib_ptr, "gi_signal_info_get_flags"),
        .gi_struct_info_get_field = try_find_sym(gir_lib_ptr, "gi_struct_info_get_field"),
        .gi_struct_info_find_field = try_find_sym(gir_lib_ptr, "gi_struct_info_find_field"),
        .gi_struct_info_get_n_methods = try_find_sym(gir_lib_ptr, "gi_struct_info_get_n_methods"),
        .gi_struct_info_get_method = try_find_sym(gir_lib_ptr, "gi_struct_info_get_method"),
        .gi_struct_info_find_method = try_find_sym(gir_lib_ptr, "gi_struct_info_find_method"),
        .gi_struct_info_get_size = try_find_sym(gir_lib_ptr, "gi_struct_info_get_size"),
        .gi_struct_info_get_alignment = try_find_sym(gir_lib_ptr, "gi_struct_info_get_alignment"),
        .gi_struct_info_is_gtype_struct = try_find_sym(gir_lib_ptr, "gi_struct_info_is_gtype_struct"),
        .gi_struct_info_is_foreign = try_find_sym(gir_lib_ptr, "gi_struct_info_is_foreign"),
        .gi_struct_info_get_copy_function_name = try_find_sym(gir_lib_ptr, "gi_struct_info_get_copy_function_name"),
        .gi_struct_info_get_free_function_name = try_find_sym(gir_lib_ptr, "gi_struct_info_get_free_function_name"),
        .gi_struct_info_get_n_fields = try_find_sym(gir_lib_ptr, "gi_struct_info_get_n_fields"),
        .gi_type_info_is_pointer = try_find_sym(gir_lib_ptr, "gi_type_info_is_pointer"),
        .gi_type_info_get_tag = try_find_sym(gir_lib_ptr, "gi_type_info_get_tag"),
        .gi_type_info_get_param_type = try_find_sym(gir_lib_ptr, "gi_type_info_get_param_type"),
        .gi_type_info_get_interface = try_find_sym(gir_lib_ptr, "gi_type_info_get_interface"),
        .gi_type_info_get_array_length_index = try_find_sym(gir_lib_ptr, "gi_type_info_get_array_length_index"),
        .gi_type_info_get_array_fixed_size = try_find_sym(gir_lib_ptr, "gi_type_info_get_array_fixed_size"),
        .gi_type_info_is_zero_terminated = try_find_sym(gir_lib_ptr, "gi_type_info_is_zero_terminated"),
        .gi_type_info_get_array_type = try_find_sym(gir_lib_ptr, "gi_type_info_get_array_type"),
        .gi_type_info_get_storage_type = try_find_sym(gir_lib_ptr, "gi_type_info_get_storage_type"),
        .gi_type_info_argument_from_hash_pointer = try_find_sym(gir_lib_ptr, "gi_type_info_argument_from_hash_pointer"),
        .gi_type_info_hash_pointer_from_argument = try_find_sym(gir_lib_ptr, "gi_type_info_hash_pointer_from_argument"),
        .gi_type_tag_argument_from_hash_pointer = try_find_sym(gir_lib_ptr, "gi_type_tag_argument_from_hash_pointer"),
        .gi_type_tag_hash_pointer_from_argument = try_find_sym(gir_lib_ptr, "gi_type_tag_hash_pointer_from_argument"),
        .gi_type_tag_to_string = try_find_sym(gir_lib_ptr, "gi_type_tag_to_string"),
        .gi_typelib_new_from_bytes = try_find_sym(gir_lib_ptr, "gi_typelib_new_from_bytes"),
        .gi_typelib_ref = try_find_sym(gir_lib_ptr, "gi_typelib_ref"),
        .gi_typelib_unref = try_find_sym(gir_lib_ptr, "gi_typelib_unref"),
        .gi_typelib_symbol = try_find_sym(gir_lib_ptr, "gi_typelib_symbol"),
        .gi_typelib_get_namespace = try_find_sym(gir_lib_ptr, "gi_typelib_get_namespace"),
        .gi_typelib_get_type = try_find_sym(gir_lib_ptr, "gi_typelib_get_type"),
        .gi_function_info_get_type = try_find_sym(gir_lib_ptr, "gi_function_info_get_type"),
        .gi_callback_info_get_type = try_find_sym(gir_lib_ptr, "gi_callback_info_get_type"),
        .gi_registered_type_info_get_type = try_find_sym(gir_lib_ptr, "gi_registered_type_info_get_type"),
        .gi_struct_info_get_type = try_find_sym(gir_lib_ptr, "gi_struct_info_get_type"),
        .gi_union_info_get_type = try_find_sym(gir_lib_ptr, "gi_union_info_get_type"),
        .gi_enum_info_get_type = try_find_sym(gir_lib_ptr, "gi_enum_info_get_type"),
        .gi_flags_info_get_type = try_find_sym(gir_lib_ptr, "gi_flags_info_get_type"),
        .gi_object_info_get_type = try_find_sym(gir_lib_ptr, "gi_object_info_get_type"),
        .gi_interface_info_get_type = try_find_sym(gir_lib_ptr, "gi_interface_info_get_type"),
        .gi_constant_info_get_type = try_find_sym(gir_lib_ptr, "gi_constant_info_get_type"),
        .gi_value_info_get_type = try_find_sym(gir_lib_ptr, "gi_value_info_get_type"),
        .gi_signal_info_get_type = try_find_sym(gir_lib_ptr, "gi_signal_info_get_type"),
        .gi_vfunc_info_get_type = try_find_sym(gir_lib_ptr, "gi_vfunc_info_get_type"),
        .gi_property_info_get_type = try_find_sym(gir_lib_ptr, "gi_property_info_get_type"),
        .gi_field_info_get_type = try_find_sym(gir_lib_ptr, "gi_field_info_get_type"),
        .gi_arg_info_get_type = try_find_sym(gir_lib_ptr, "gi_arg_info_get_type"),
        .gi_type_info_get_type = try_find_sym(gir_lib_ptr, "gi_type_info_get_type"),
        .gi_unresolved_info_get_type = try_find_sym(gir_lib_ptr, "gi_unresolved_info_get_type"),
        .gi_callable_info_get_type = try_find_sym(gir_lib_ptr, "gi_callable_info_get_type"),
        .gi_union_info_get_field = try_find_sym(gir_lib_ptr, "gi_union_info_get_field"),
        .gi_union_info_get_n_methods = try_find_sym(gir_lib_ptr, "gi_union_info_get_n_methods"),
        .gi_union_info_get_method = try_find_sym(gir_lib_ptr, "gi_union_info_get_method"),
        .gi_union_info_is_discriminated = try_find_sym(gir_lib_ptr, "gi_union_info_is_discriminated"),
        .gi_union_info_get_discriminator_offset = try_find_sym(gir_lib_ptr, "gi_union_info_get_discriminator_offset"),
        .gi_union_info_get_discriminator_type = try_find_sym(gir_lib_ptr, "gi_union_info_get_discriminator_type"),
        .gi_union_info_get_discriminator = try_find_sym(gir_lib_ptr, "gi_union_info_get_discriminator"),
        .gi_union_info_find_method = try_find_sym(gir_lib_ptr, "gi_union_info_find_method"),
        .gi_union_info_get_size = try_find_sym(gir_lib_ptr, "gi_union_info_get_size"),
        .gi_union_info_get_alignment = try_find_sym(gir_lib_ptr, "gi_union_info_get_alignment"),
        .gi_union_info_get_copy_function_name = try_find_sym(gir_lib_ptr, "gi_union_info_get_copy_function_name"),
        .gi_union_info_get_free_function_name = try_find_sym(gir_lib_ptr, "gi_union_info_get_free_function_name"),
        .gi_union_info_get_n_fields = try_find_sym(gir_lib_ptr, "gi_union_info_get_n_fields"),
        .gi_value_info_get_value = try_find_sym(gir_lib_ptr, "gi_value_info_get_value"),
        .gi_vfunc_info_get_offset = try_find_sym(gir_lib_ptr, "gi_vfunc_info_get_offset"),
        .gi_vfunc_info_get_signal = try_find_sym(gir_lib_ptr, "gi_vfunc_info_get_signal"),
        .gi_vfunc_info_get_invoker = try_find_sym(gir_lib_ptr, "gi_vfunc_info_get_invoker"),
        .gi_vfunc_info_get_address = try_find_sym(gir_lib_ptr, "gi_vfunc_info_get_address"),
        .gi_vfunc_info_invoke = try_find_sym(gir_lib_ptr, "gi_vfunc_info_invoke"),
        .gi_vfunc_info_get_flags = try_find_sym(gir_lib_ptr, "gi_vfunc_info_get_flags"),
    };

// INIT_STRUCT_HERE

}

void close_gir(void) {
    cosmo_dlclose(girepository->lib);
    free(girepository);
}
